# Generated by Django 3.1.1 on 2020-09-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
