# Generated by Django 3.1.1 on 2020-09-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200924_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
