# Generated by Django 3.1.1 on 2020-10-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20201002_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('esewa', 'esewa')], default='Cash on delivery', max_length=50),
        ),
    ]
