# Generated by Django 3.1.1 on 2020-10-06 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.order'),
        ),
    ]
