# Generated by Django 3.1.1 on 2020-10-06 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_checkout_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('esewa', 'esewa')], default='Cash on delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.checkout'),
        ),
    ]
