# Generated by Django 3.1.1 on 2020-10-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('esewa', 'esewa')], default='Cash on delivery', max_length=50),
        ),
    ]
