# Generated by Django 3.1.1 on 2020-10-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20201006_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['updated']},
        ),
    ]
