# Generated by Django 3.1.1 on 2020-10-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20201009_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='appartment_no',
            new_name='appartment',
        ),
    ]
