# Generated by Django 3.1.1 on 2020-10-09 09:39

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20201009_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(to='product.Category'),
        ),
    ]
