# Generated by Django 3.1.1 on 2020-10-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20201009_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('esewa', 'esewa')], default='Cash on delivery', max_length=50),
        ),
    ]
