# Generated by Django 3.1.1 on 2020-10-15 10:18

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20201015_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(null=True, to='product.Category'),
        ),
    ]
