# Generated by Django 3.1.1 on 2020-10-15 10:40

from django.db import migrations
import django.db.models.deletion
import treewidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20201015_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category'),
        ),
    ]
