# Generated by Django 3.1.1 on 2020-10-15 10:41

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20201015_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(to='product.Category'),
        ),
    ]
