# Generated by Django 3.1.1 on 2020-10-15 10:42

from django.db import migrations
import treewidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20201015_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=treewidget.fields.TreeManyToManyField(to='product.Category'),
        ),
    ]
